server:
  port: 8083

spring:
  application:
    name: telemetry-bff
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bff-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/telemetry-realm
